Topics mobile carousel
usdoj-crt/beta-ada pull request #653
Opened 2023-07-24 15:09 UTC by kewitham

2023-07-24 18:25 UTC, okkays commented
@kewitham can you take a look at the ci/cd failures?

2023-07-24 18:50 UTC, okkays requested changes

2023-07-24 18:50 UTC, okkays commented on _assets/js/carousel.js
> +  }
this looks like a compatibility layer, but we can just use elements.forEach

2023-07-24 18:50 UTC, okkays commented on _assets/js/carousel.js
> +  }
ditto, el.classList.contains is supported well enough for us to use

2023-07-24 18:50 UTC, okkays commented on _assets/js/carousel.js
> +    if (settings.slidenav || settings.animate) {
this might read better inverted

```
if (!settings.slidenav || !settings.animate) return;
```

2023-07-24 18:50 UTC, okkays commented on _assets/js/carousel.js
> +const mobileCarousel = () => {
why not:
```suggestion
function mobileCarousel() {
```

2023-07-24 18:50 UTC, okkays commented on _assets/js/carousel.js
> +  // the play button.
prefer JSDoc (`/** */`) to implementation comments (`//`) for function documentation

Editors and tooling such as vscode are more likely to pick up on JSDoc than implementation comments.

2023-07-24 18:50 UTC, okkays commented on _assets/js/carousel.js
> +  function init(set) {
this function is very long. It'd be nice to have it broken out into meaningful helper functions, such as:

function init(set) {
  initControls(set);
  initSlidenav(set);
  ...
}

2023-07-24 18:50 UTC, okkays commented on _assets/js/carousel.js
> +              if (settings.startAnimated) {
Use guard clauses to flatten this code.

It's hard to visually tie the ifs to the else ifs, so [it's hard to see bugs like this](https://testing.googleblog.com/2017/06/code-health-reduce-nesting-reduce.html) which might appear

2023-07-24 18:50 UTC, okkays commented on _assets/js/carousel.js
> +      }
```suggestion
      if (!hasClass(slide, 'current')) return;
      if (!setFocus) return;
      slide.setAttribute('tabindex', '-1');
      slide.focus();
      setFocus = false;
```

2023-07-24 18:50 UTC, okkays commented on _assets/js/carousel.js
> +    // the previous slide is the last of the slides.
Suggest removing; this comment restates the code below it - [it doesn't explain why](https://blog.codinghorror.com/code-tells-you-how-comments-tell-you-why/)

```suggestion
```

2023-07-24 18:50 UTC, okkays commented on _assets/js/carousel.js
> +    for (let i = slides.length - 1; i >= 0; i--) {
prefer arrayFunctions (`forEach`) to count controlled loops

2023-07-24 18:50 UTC, okkays commented on _assets/js/carousel.js
> +      for (let j = buttons.length - 1; j >= 0; j--) {
refactor to use forEach

2023-07-24 18:50 UTC, okkays commented on _assets/js/carousel.js
> +    let length = slides.length,
prefer `const` to `let` where possible
```suggestion
    const length = slides.length,
```

2023-07-24 18:50 UTC, okkays commented on _assets/js/carousel.js
> +  let animationSuspended;
if it's necessary to have a global context like this, consider namespacing it so it's more obvious where the variables come from when we're 200 lines down the page.

```suggestion
  const context = {
      carousel: undefined,
      slides: undefined,
      index: undefined,
      slidenav: undefined,
      settings: undefined,
      timer: undefined,
      setFocus: undefined,
      animationSuspended: undefined,
  };
```

Also consider giving them sensible defaults (animationSuspended probably makes more sense as `false` than `undefined`

2023-07-24 18:50 UTC, okkays commented on _assets/js/carousel.js
> +  // Function to stop the animation
```suggestion
```

2023-07-24 18:50 UTC, okkays commented on _assets/js/carousel.js
> +  // Function to start the animation
```suggestion
```

2023-07-24 18:50 UTC, okkays commented on _assets/js/carousel.js
> +  // Function to suspend the animation
```suggestion
```

2023-07-24 18:50 UTC, okkays commented on _assets/js/carousel.js
> +    }
```suggestion
    if (!settings.animate)
    clearTimeout(timer);
    settings.animate = false;
    animationSuspended = true;
```

2023-07-27 22:12 UTC, vwilliamsn commented
7/27 update - @kewitham we should have an image for you hopefully tomorrow. @c2nelson found an image, we're awaiting approve to use that image.

2023-07-28 15:46 UTC, vwilliamsn approved these changes
LGTM! Thanks @kewitham!

2023-07-31 18:09 UTC, okkays approved these changes
LGTM! Thanks for dealing with my style nits :D

2023-07-31 18:09 UTC, okkays commented on _assets/js/carousel.js
> +/* Initialization for the carousel
```suggestion
/** Initialization for the carousel
```

2023-07-31 19:13 UTC, merged