Add hero image and cards to law and regs LP
usdoj-crt/beta-ada pull request #687
Opened 2023-08-30 13:36 UTC by kewitham

This PR updates the law and regs landing page to have a hero image and cards linking to the individual law and regs, mirroring the design of the topics landing page.

<img width="678" alt="Screenshot 2023-08-30 at 8 35 26 AM" src="https://github.com/usdoj-crt/beta-ada/assets/18104884/8adcb5f0-ba48-4a66-b442-bd98179fd07b">
<img width="678" alt="Screenshot 2023-08-30 at 8 35 39 AM" src="https://github.com/usdoj-crt/beta-ada/assets/18104884/2e097ba6-0352-4fc0-9b87-f5f6b67bf3c3">

2023-09-28 14:08 UTC, okkays requested changes
Can you take a look at why the pages build is failing?

2023-09-28 19:18 UTC, okkays approved these changes

2023-10-16 12:09 UTC, sanchez-amanda approved these changes

2023-10-24 20:10 UTC, vwilliamsn commented
10/24 update - thanks @kewitham for your work on this. The last "landing" page that we updated on the site was the Topics page (Tina worked on this). @sanchez-amanda I'd hoped that part of your work on the law and regs would include reworking the landing page (as it's doing a lot of work).  Minimally, it would be nice for the Topics and Law/Reg/Standards page to have a [similar look & feel](https://www.ada.gov/topics/). The hero image & tile cards are a step in the right direction, can we also look to incorporate some of the other features/functionality?

The teams doing great work to improve the functionality of the legal documents, can't wait to see/hear your recommendations on how we can take it to the next level. Happy to chat to flush out the details and answer any questions you might have.

cc: @randyabramson

2024-01-02 18:13 UTC, closed without merging