Update file a complaint form link
usdoj-crt/beta-ada pull request #706
Opened 2023-10-12 16:16 UTC by kewitham

This PR updates the file a complaint form link with the new form.

2023-10-13 13:51 UTC, vwilliamsn commented
@kewitham - something wacky is going on with the form. 

![image](https://github.com/usdoj-crt/beta-ada/assets/96496943/011c2dff-b103-488b-b92f-ecc4fc3b27e5)
![image](https://github.com/usdoj-crt/beta-ada/assets/96496943/b7997984-c791-4114-ac9a-476a6cea60c2)

2023-10-13 15:40 UTC, kewitham commented
> @kewitham - something wacky is going on with the form.
> 
> ![image](https://user-images.githubusercontent.com/96496943/274919684-011c2dff-b103-488b-b92f-ecc4fc3b27e5.png) ![image](https://user-images.githubusercontent.com/96496943/274919111-b7997984-c791-4114-ac9a-476a6cea60c2.png)

reached out to Randy to get a clean copy

2023-10-13 18:18 UTC, vwilliamsn commented
Updated link work great - one small change on the form @randyabramson - for consistency purposes each section is numbered - the blue circle (see image) should have "5" inside of it. 

![image](https://github.com/usdoj-crt/beta-ada/assets/96496943/07644b7e-5d0f-467c-a306-f3c7833875ba)

2023-10-13 18:25 UTC, vwilliamsn commented
@randyabramson - a couple of minor inconsistencies in the form. Should the text be blue or black?

![image](https://github.com/usdoj-crt/beta-ada/assets/96496943/6e71d4e4-916a-47fa-ad11-3701e735e82a)
![image](https://github.com/usdoj-crt/beta-ada/assets/96496943/a5f1c3d9-26f1-43e5-b8dc-1602cb7bd456)
![image](https://github.com/usdoj-crt/beta-ada/assets/96496943/7c4e70c5-6e70-4b80-8b2e-39b45af27993)
![image](https://github.com/usdoj-crt/beta-ada/assets/96496943/6bd6c481-42d7-4201-9fba-96ef86d84f59)
![image](https://github.com/usdoj-crt/beta-ada/assets/96496943/45cf913c-63d0-4af4-8173-a6e05893e12d)
![image](https://github.com/usdoj-crt/beta-ada/assets/96496943/28a285da-4088-44c3-9ff4-49e5e395d7d6)
![image](https://github.com/usdoj-crt/beta-ada/assets/96496943/72278565-c0f7-403b-8ebf-d2958cd00ce1)
![image](https://github.com/usdoj-crt/beta-ada/assets/96496943/66d309e7-891a-4096-8fc3-741e6c16b8f8)

cc: @kewitham

2023-10-13 18:33 UTC, randyabramson commented
@vwilliamsn - I'm not seeing the blue/black issue above on the clean PDF. Again, I think github is mangling this PDF, so I sent Katie the clean PDF.

2023-10-13 18:40 UTC, vwilliamsn commented
> @vwilliamsn - I'm not seeing the blue/black issue above on the clean PDF. Again, I think github is mangling this PDF, so I sent Katie the clean PDF.

@randyabramson - When you preview the document using the "Preview in Federalist link" the document is wonky.  @kewitham is they any way to see if it's just not displaying properly in the preview function but will display properly once live on the site?

2023-10-17 14:11 UTC, okkays requested changes
@kewitham @vwilliamsn fwiw I don't think the current inconsistencies are federalist's fault - See [the raw file attached to github](https://github.com/usdoj-crt/beta-ada/blob/940b982094613ab17e7b5a4d4aa3d2c16dd51535/_pdfs/file-a-complaint.pdf).

Once at the page above, use the "download raw file" button on the right of the page to open it with your usual pdf viewer:

<img width="1512" alt="image" src="https://github.com/usdoj-crt/beta-ada/assets/15126660/25a24ac5-b4b4-42e0-8ccb-0b754af76759">

I'm guessing this is a problem with the source PDF

2023-10-17 15:21 UTC, kewitham commented
> @kewitham @vwilliamsn fwiw I don't think the current inconsistencies are federalist's fault - See [the raw file attached to github](https://github.com/usdoj-crt/beta-ada/blob/940b982094613ab17e7b5a4d4aa3d2c16dd51535/_pdfs/file-a-complaint.pdf).
> 
> Once at the page above, use the "download raw file" button on the right of the page to open it with your usual pdf viewer:
> 
> <img alt="image" width="1512" src="https://user-images.githubusercontent.com/15126660/275862429-25a24ac5-b4b4-42e0-8ccb-0b754af76759.png">
> I'm guessing this is a problem with the source PDF

@okkays touched base with Randy on this and Kavitha is going to send an updated version with these issues fixed.

2023-11-16 21:45 UTC, vwilliamsn approved these changes
LGTM thanks @kewitham!

2023-11-17 14:39 UTC, okkays approved these changes

2023-11-17 14:39 UTC, okkays commented on _pages/file-a-complaint.md
> +<span>Fill out and send the paper ADA Complaint Form (<a class="pa11y-skip file-a-complaint" data-ga-event-name="ADA complaint form 1 file a complaint link" href="{{'assets/_pdfs/file-a-complaint.pdf
yess you are the best, thank you for not using {% asset %}!

2023-11-20 14:51 UTC, merged

2023-12-05 22:16 UTC, vwilliamsn commented
Completed and PR was merged 2 weeks ago.