Law regs redesign
usdoj-crt/beta-ada pull request #732
Opened 2023-12-28 20:55 UTC by kewitham

2024-01-03 15:47 UTC, okkays requested changes
Code LGTM!

I'd just double check how things work on mobile

2024-01-03 15:47 UTC, okkays commented on _includes/landing/law-reg-tiles.html
> +    </div>
These don't appear to be scaling well to mobile:

<img width="393" alt="image" src="https://github.com/usdoj-crt/beta-ada/assets/15126660/22ee0571-01c8-424b-9458-50ab861aa390">

2024-01-04 13:11 UTC, vwilliamsn commented
@kewitham - Here are some of my suggested edits based on the standards subpage screenshot that @sanchez-amanda provided late yesterday:

•	I think it would be helpful to include hyperlinks so that folks can access these documents in multiple places on this page. See here for example:  “[1991 ADA Standards](https://www.ada.gov/1991standards/1991standards-archive.html)” and adopted revised ADA Standards on September 15, 2010, known as the “[2010 ADA Standards](https://www.ada.gov/regs2010/2010ADAStandards/2010ADAstandards.htm)”, along with the [Guidance on the 2010 Standards](https://www.ada.gov/regs2010/2010ADAStandards/Guidance2010ADAstandards.htm).  

•	Remove the last sentence in the new paragraph under Versions of the ADA Standards – “In 2011, the Department issued…..”  as it’s repetitive with a sentence in the next paragraph.
 
Happy to discuss at tomorrow’s meeting if you have questions.

2024-01-04 13:13 UTC, vwilliamsn commented
@kewitham for all of the newly redesigned pages please update the left side navigation:

•	In the side navigation it should be “Title II Regulation” (singular) and “Title III Regulation” (singular).

cc: @sanchez-amanda

2024-01-04 13:33 UTC, vwilliamsn commented
@kewitham @sanchez-amanda - in the hamburger feature is there a way to show that the Law, Regs & Standards is a landing page and the ADA, Regulations & Standards are subpages?

Also, can we make changes to the hamburger feature, left navigation, landing page title and info boxes so that it reads: _Law, Regulations & Standards._

Thanks!

2024-01-04 21:28 UTC, kewitham commented
@sanchez-amanda @vwilliamsn made the updates based on your feedback - let me know if I missed anything!

2024-01-04 23:19 UTC, vwilliamsn commented
Great job, @kewitham! I took a quick glance and spotted a couple of places that need a minor tweak or two. I'll take a deeper look tomorrow.

Change requested for: 1) all the Info boxes should read 'Law" (singular – see image below) & 2) add hyperlink to Guidance on the 2010 Standards in the paragraph under Versions of the ADA Standards (see image below)


![image](https://github.com/usdoj-crt/beta-ada/assets/96496943/f9bf6db0-70d6-4a7a-901d-8ecd43f1ef83)
![image](https://github.com/usdoj-crt/beta-ada/assets/96496943/d3994001-c9ff-4fc9-9d8b-bc845882c752)

 cc: @sanchez-amanda

2024-01-09 16:53 UTC, vwilliamsn commented
> @sanchez-amanda @vwilliamsn made the updates based on your feedback - let me know if I missed anything!

LGTM! Thanks @kewitham. I'm going to provide the federalist link to leadership for their review. cc: @sanchez-amanda

2024-01-10 16:25 UTC, vwilliamsn commented
@kewitham, I received a request to make changes to the heading (below)
![image](https://github.com/usdoj-crt/beta-ada/assets/96496943/48ff3839-1ecd-4496-908d-b28254d96b3a)

Please change it to: Proposed Changes to Our Regulations.

cc: @sanchez-amanda

2024-01-29 21:24 UTC, vwilliamsn commented
@kewitham - here are some edits from leadership. We are still holding for final approval.

1) [Leadership requested changes to homepage for Law, Regs and Standards.docx](https://github.com/usdoj-crt/beta-ada/files/14088699/Leadership.requested.changes.to.homepage.for.Law.Regs.and.Standards.docx)

Info line recommendation - Consider adding images to the Reg subpage and make the images clickable (for consistency with the design standards page).
<img width="305" alt="t2-reg-cover" src="https://github.com/usdoj-crt/beta-ada/assets/96496943/6db8248b-78f2-422e-b9aa-e4a3e7f13ccb">
<img width="300" alt="t3-reg-cover" src="https://github.com/usdoj-crt/beta-ada/assets/96496943/d250e7ee-d0d3-4470-9c38-0981cf42a610">

2024-02-01 21:33 UTC, kewitham commented
Closing this out as the changes now exist in a new [PR](https://github.com/usdoj-crt/beta-ada/pull/748) here to deal with conflicts.

2024-02-01 21:33 UTC, closed without merging