Faceted search mock
usdoj-crt/beta-ada pull request #746
Opened 2024-01-30 18:45 UTC by kewitham

![image](https://github.com/usdoj-crt/beta-ada/assets/18104884/316d70dc-b31d-491e-8c3f-7aec5d4cb9be)

2024-02-02 15:24 UTC, okkays requested changes
code looking good, some style comments

2024-02-02 15:24 UTC, okkays commented on assets/js/pagination.js
> +import { _ } from 'core-js';
can you add a comment to explain what this is polyfilling?

2024-02-02 15:24 UTC, okkays commented on assets/js/pagination.js
> + // audience: urlParams.get('audience'),
(remove commented out code)

2024-02-02 15:24 UTC, okkays commented on assets/js/pagination.js
> +  }
```suggestion
checkbox.setAttribute('data-checked', checkbox.value === audience);
```

2024-02-02 15:24 UTC, okkays commented on assets/js/utils/renderSearchPage.js
> +export default function renderSearchPage(searchResults, urlParams, numberOfResults, audience = null) {
You should be able to do this without the default parameter - in javascript, by default, parameters that aren't specified will be `undefined`

```suggestion
export default function renderSearchPage(searchResults, urlParams, numberOfResults, audience) {
```

2024-02-02 15:24 UTC, okkays commented on assets/js/utils/renderSearchPage.js
> +      return null
```suggestion
      return null;
```

2024-02-12 15:02 UTC, okkays requested changes
Missed something, sorry!

2024-02-12 15:03 UTC, vwilliamsn commented
@kewitham great job! Quick question about facet search, I tried searching for "door & doors" using the Topics filter and it only surfaces the 'Voting' overlay. Door(s) also appears in the State and Local Government & Businesses That Are Open to the Public however it's behind the accordion feature. Can the search pull from something that’s hidden behind the accordion feature?

2024-02-12 19:24 UTC, kewitham commented
> @kewitham great job! Quick question about facet search, I tried searching for "door & doors" using the Topics filter and it only surfaces the 'Voting' overlay. Door(s) also appears in the State and Local Government & Businesses That Are Open to the Public however it's behind the accordion feature. Can the search pull from something that’s hidden behind the accordion feature?

@vwilliamsn the filter won't change which results are surfaced for certain keywords and I don't see that result coming up on the regular search currently on the site. It should pull it even though it's in an accordion though. Maybe we can investigate updating the meta data to include that keyword. Do you want me to create a ticket for that?

2024-02-13 16:17 UTC, sanchez-amanda commented
A few style thoughts that i put in this screenshot - mostly moving headers around to match the style of guidance and resources page.

- Move 'Search' header to top of results column (like guidance and resources page)
- Once header is moved, move ‘document type’ so that the top of the text lines up with ‘Search’ - similar to Guidance and Resource Materials
- Open Question: did we want to add descriptors to the document types? tooltip? not necessary for approval but just curious where we landed with that

<img width="1031" alt="Screenshot 2024-02-13 at 11 15 20 AM" src="https://github.com/usdoj-crt/beta-ada/assets/138693933/b2c3e433-3f06-4475-9b35-942f9b936ffe">

@kewitham @vwilliamsn

2024-02-13 17:50 UTC, vwilliamsn commented
@sanchez-amanda - love that suggestion. I think having descriptors or a tooltip would give folks more of an understanding of the new filter options and how that might improve their search results. Do you have a recommendation - should we use the info box brief description or a more detail description of the different content types?

@kewitham - on the left side, we list the content types, can we mirror the global navigation wording. What's the lift for adding descriptors or a tooltip feature?
![image](https://github.com/usdoj-crt/beta-ada/assets/96496943/d01e639e-6fb5-42c2-9089-3092d2398899)

2024-02-15 16:55 UTC, kewitham commented
@vwilliamsn @sanchez-amanda sounds good! yes I actually already added a tooltip (for some reason the icon isn't showing up in the federalist preview). Right now the language I have is: "Basic overview" for Topics, "Detailed guidance" for Resources and "Legal documents" for Law and Regulations.

2024-02-22 17:19 UTC, kewitham commented
@vwilliamsn @sanchez-amanda made the requested updates!

2024-02-27 14:50 UTC, okkays approved these changes
LGTM!

2024-05-15 15:01 UTC, merged