In page search mobile
usdoj-crt/beta-ada pull request #782
Opened 2024-04-05 20:58 UTC by kewitham

2024-04-16 20:39 UTC, kewitham commented on assets/js/laws-regs-parser.js
> +    section.classList.remove('searched');
Thanks for this! Made these changes - could you take a look and lmk what you think?

2024-04-19 14:18 UTC, okkays requested changes
Nice! jumping between results is good now

Pressing enter still has a bug, but I think it's minor

2024-04-19 14:18 UTC, okkays commented on assets/js/laws-regs-parser.js
> +    let newSection = section.cloneNode(true);
```suggestion
    const newSection = section.cloneNode(true);
```

2024-04-19 14:18 UTC, okkays commented on assets/js/laws-regs-parser.js
> +    section.parentNode.replaceChildren(newSection);
👍 👍 nice

2024-04-19 14:18 UTC, okkays commented on assets/js/laws-regs-parser.js
> +  // searchBox.focus();
(remove commented out code)

2024-04-19 14:18 UTC, okkays commented on assets/js/laws-regs-parser.js
> +    }
Jumping between results is now quick, but I'm still seeing slow performance on this event. The chrome profiler seems to indicate that it's calling this code ten times:

<img width="489" alt="image" src="https://github.com/usdoj-crt/beta-ada/assets/15126660/63d84cd9-ac9d-47bd-8dfe-626c1d8e9985">

Ah - it looks like you're calling initSearch on input, which is going to add a keydown listener whenever you type into the box:

<img width="476" alt="image" src="https://github.com/usdoj-crt/beta-ada/assets/15126660/8699fc58-dd97-45e3-81ef-e0c6708ce1b6">

Yep - for this search, I typed `waffles the best I love them` then replaced it with `dog` and searched. The function is called once for every character in my search query:

<img width="647" alt="image" src="https://github.com/usdoj-crt/beta-ada/assets/15126660/9577d93a-a948-4576-bed8-e680e8f61ad9">

2024-05-16 20:06 UTC, okkays approved these changes
A bunch of small things; otherwise lgtm!

2024-05-16 20:06 UTC, okkays commented on assets/js/laws-regs-parser.js
> +    if (e.keyCode != 9) {
[keyCode is deprecated](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode)

it really looks like `key == 'Tab'` is the best alternative, as the replacement `code` [has terrible support](https://caniuse.com/?search=keyboardevent.code)

2024-05-16 20:06 UTC, okkays commented on assets/js/laws-regs-parser.js
> +  console.log('hit input');
remove console log

2024-05-16 20:06 UTC, okkays commented on assets/js/laws-regs-parser.js
> +  console.log('hit search');
nit: remove

2024-05-16 20:06 UTC, okkays commented on assets/js/laws-regs-parser.js
> +  // searchGo.classList.remove('listening');
nit: remove

2024-05-16 20:06 UTC, okkays commented on assets/js/laws-regs-parser.js
> +    // if (!searchGo.classList.contains('display-none')) {
remove commented out code

2024-06-14 18:19 UTC, vwilliamsn approved these changes
LGTM, great job @kewitham!

2024-06-21 13:42 UTC, closed without merging