[ADA-1088] Add community outreach content
usdoj-crt/beta-ada pull request #857
Opened 2024-12-18 20:11 UTC by Rwolfe-Nava

2024-12-19 16:35 UTC, c2nelson commented
@Rwolfe-Nava The link is throwing a 404 error.  Could it be because you've populated a redirect?  This is a new page so a redirect isn't necessary.  Just a thought.

2024-12-19 16:48 UTC, Rwolfe-Nava commented
I noticed that as well with federalist. The page does not throw a 404 and all of the links work fine locally so its a bit tricky to nail down. 

Thank you for the insight though, I will try removing the redirect. If there is anything else you can think it might be please let me know

2024-12-19 18:30 UTC, vwilliamsn commented
@Rwolfe-Nava - thanks for your work on this. Can you add a video of what you're seeing locally? I'm also getting the 404 page and the federalist link shows a redirect (when it's a new page). https://www.ada.gov/preview/usdoj-crt/beta-ada/rw/1088-outreach-content/_pages/redirects/communityoutreach/

2024-12-19 18:49 UTC, Rwolfe-Nava commented
@vwilliamsn It makes sense that it is redirecting to the 404 page if it can't find the new page for some reason. I have removed the redirect that @c2nelson was referring to and it did not fix the problem in federalist. 

I added two GIFs to the original post description showing my local environment. One for desktop mode and one for mobile mode in my browser.

2024-12-19 18:51 UTC, vwilliamsn commented
> @vwilliamsn It makes sense that it is redirecting to the 404 page if it can't find the new page for some reason. I have removed the redirect that @c2nelson was referring to and it did not fix the problem in federalist.
> 
> I added two GIFs to the original post description showing my local environment. One for desktop mode and one for mobile mode in my browser.

@Rwolfe-Nava - thank you!!!

2025-01-03 19:29 UTC, Rwolfe-Nava commented
@okkays When you have time to review this please look into the 404 issue in the federalist for this new page. I modeled this off of your PR for the 'help' page, which doesn't seem to get a 404 in the federalist preview. So I am not sure if the 404 in this case is catching a bug in my code or not. 

It seems to function locally, but I am not sure how else we can test to make sure this is good to go. Thank you!

2025-01-06 19:23 UTC, okkays commented
@Rwolfe-Nava there is an existing redirect in place for `/communityoutreach`. These redirects don't happen locally (there are a lot of them, so we turn them off locally to be able to develop faster) but they do happen on preview. That's why it's pushing you to `ada.gov` instead of remaining on the preview domain, as well.

Deleting this file (which is no longer necessary) should fix it: `_pages/redirects/communityoutreach.md`

2025-01-06 19:24 UTC, okkays requested changes
(Remove `_pages/redirects/communityoutreach.md`)

2025-01-06 20:20 UTC, vwilliamsn commented
@Rwolfe-Nava - per the mock, please add ![image](https://github.com/user-attachments/assets/abf47a38-aa47-433e-859d-0fd4f4f3efa9) under the left side navigation.

2025-01-07 17:08 UTC, vwilliamsn commented
> @vwilliamsn - Good catch. It has now been added and can been seen in federalist preview

Thanks @Rwolfe-Nava! Your preview gifs (above) show the icons in the Presentation/Participation box & Information Sharing box, however in the federalist link the icons are missing. Any idea why?

2025-01-07 18:06 UTC, Rwolfe-Nava commented
@vwilliamsn Thanks, I see that issue too. It looks like for some reason the images either do not exist on the federalist build, or it cannot find them. (It's returning a 404 error when trying to load the icons). Looking into it now.

2025-01-07 18:28 UTC, Rwolfe-Nava commented
@vwilliamsn  Just pushed a commit that seems to have fixed the issue with icons not loading properly in federalist.

2025-01-07 19:56 UTC, vwilliamsn commented
Hey @kavithakrishnan4 - can you take a quick look at the pull request. Please confirm that the spacing in the boxes align with your vision and specs for the page. Thanks!

2025-01-07 20:21 UTC, kavithakrishnan4 commented
@vwilliamsn @Rwolfe-Nava Everything looks good to me.

2025-01-08 18:03 UTC, vwilliamsn approved these changes
LGTM! Great job, Richard!

2025-01-08 18:23 UTC, okkays approved these changes
lgtm!

2025-01-08 18:27 UTC, merged